In [1]:
import pandas as pd
import numpy as np

In [10]:
### Create a numpy array containing the numbers from 1 to 10, and then reshape it to a 2x5 matrix.

In [8]:
arr1 = np.arange(1,11)

In [5]:
print(arr1)

[ 1  2  3  4  5  6  7  8  9 10]


In [7]:
arr1_reshape=arr1.reshape(2,5)
print(arr1_reshape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [11]:
### Create a numpy array containing the numbers from 1 to 20, and then extract the elements between the 5th and 15th index.

In [12]:
arr1 = np.arange(1,21)

In [13]:
arr1[5:16]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [14]:
### Create a Pandas series with the following data: {'apples': 3, 'bananas': 2, 'oranges': 1}. Then, add a new item to the series with the key 'pears' and the value 4.

In [16]:
fruits = pd.Series({'apples': 3, 'bananas': 2, 'oranges': 1})
fruits

apples     3
bananas    2
oranges    1
dtype: int64

In [19]:
fruits['pears'] = 4  
print(fruits)

apples     3
bananas    2
oranges    1
pears      4
dtype: int64


In [20]:
### Create a dataframe with the following columns: name, age, and gender. The dataframe should have 10 rows of data.

In [23]:
data = {
    'name': ['John', 'Alice', 'Bob', 'David', 'Emma', 'Frank', 'Grace', 'Helen', 'Ivy', 'Jack'],
    'age': [25, 34, 28, 40, 22, 30, 45, 27, 35, 29],
    'gender': ['Male', 'Female', 'Male', 'Male', 'Female', 'Male', 'Female', 'Female', 'Female', 'Male']
}
df = pd.DataFrame(data)
print(df)

    name  age  gender
0   John   25    Male
1  Alice   34  Female
2    Bob   28    Male
3  David   40    Male
4   Emma   22  Female
5  Frank   30    Male
6  Grace   45  Female
7  Helen   27  Female
8    Ivy   35  Female
9   Jack   29    Male


In [24]:
### Add a new column to the data frame created in question 1, called occupation. The values for this column should be Programmer, Manager, and Analyst, corresponding to the rows in the dataframe.

In [25]:
df['occupation'] = ['Programmer', 'Manager', 'Analyst', 'Manager', 'Programmer', 'Analyst', 'Manager', 'Programmer', 'Analyst', 'Manager']
print(df)

    name  age  gender  occupation
0   John   25    Male  Programmer
1  Alice   34  Female     Manager
2    Bob   28    Male     Analyst
3  David   40    Male     Manager
4   Emma   22  Female  Programmer
5  Frank   30    Male     Analyst
6  Grace   45  Female     Manager
7  Helen   27  Female  Programmer
8    Ivy   35  Female     Analyst
9   Jack   29    Male     Manager


In [26]:
### Select the rows of the dataframe where the age is greater than or equal to 30.

In [27]:
age_df = df[df['age'] >= 30]
print(age_df)

    name  age  gender occupation
1  Alice   34  Female    Manager
3  David   40    Male    Manager
5  Frank   30    Male    Analyst
6  Grace   45  Female    Manager
8    Ivy   35  Female    Analyst


In [28]:
### Convert this dataframe to a csv file and read that csv file, finally display the contents.

In [29]:
df.to_csv('employeement.csv',index=False)

In [ ]:
df_read=